#!/usr/bin/env python

import requests
import subprocess
from bs4 import BeautifulSoup

GITHUB_REPO = 'ros/ros_comm'
DEVEL_BRANCH = 'kinetic-devel'
EDGE_BRANCH = 'kinetic-edge'
ORIGIN_NAME = 'upstream'


def get_prs():
    r = requests.get('https://github.com/%s/labels/hitlist' % GITHUB_REPO)
    soup = BeautifulSoup(r.text, 'html.parser')
    links = soup.find('ul', class_='js-navigation-container').find_all('a', class_='h4')
    links.reverse()
    for link in links:
        yield (link['href'].split('/')[-1],
               'https://github.com%s.diff' % link['href'],
               link.text.strip())

subprocess.check_call(['git', 'fetch', ORIGIN_NAME])
subprocess.check_call(['git', 'clean', '-f'])
subprocess.check_call(['git', 'checkout', EDGE_BRANCH])
subprocess.check_call(['git', 'reset', '--hard', '%s/%s' % (ORIGIN_NAME, DEVEL_BRANCH)])

for number, diff_url, description in get_prs():
    print 'Applying %s' % diff_url
    diff = requests.get(diff_url).text
    subprocess.Popen(['git', 'apply'], stdin=subprocess.PIPE).communicate(diff)
    subprocess.check_call(['git', 'add', '-A'])
    subprocess.Popen(['git', 'commit', '-F', '-'], stdin=subprocess.PIPE).communicate(
        "%s (#%s)" % (description, number))
