#!/usr/bin/env python
#
# Copyright 2017 Mike Purvis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import requests
import subprocess
from bs4 import BeautifulSoup

GITHUB_REPO = 'ros/ros_comm'
DEVEL_BRANCH = 'kinetic-devel'
EDGE_BRANCH = 'kinetic-edge'
ORIGIN_NAME = 'upstream'


subprocess.check_call(['git', 'fetch', ORIGIN_NAME])
subprocess.check_call(['git', 'clean', '-f'])
subprocess.check_call(['git', 'checkout', EDGE_BRANCH])
subprocess.check_call(['git', 'reset', '--hard', '%s/%s' % (ORIGIN_NAME, DEVEL_BRANCH)])

def get_prs():
    r = requests.get('https://github.com/%s/labels/hitlist' % GITHUB_REPO)
    soup = BeautifulSoup(r.text, 'html.parser')
    links = soup.find('ul', class_='js-navigation-container').find_all('a', class_='h4')
    links.reverse()
    for link in links:
        yield (link['href'].split('/')[-1],
               'https://github.com%s.diff' % link['href'],
               link.text.strip())

for number, diff_url, description in get_prs():
    print 'Applying %s' % diff_url
    diff = requests.get(diff_url).text
    subprocess.Popen(['git', 'apply'], stdin=subprocess.PIPE).communicate(diff)
    subprocess.check_call(['git', 'add', '-A'])
    subprocess.Popen(['git', 'commit', '-F', '-'], stdin=subprocess.PIPE).communicate(
        "%s (#%s)" % (description, number))
